name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build for GitHub Pages
    runs-on: ubuntu-slim

    steps:
      - name: Git Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - name: Install NPM packages
        run: npm ci

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v6

      - name: Build Next.js
        run: |
          node --run build
          node --run postbuild

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./out

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-slim
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
